### ISSUE TITLE
Branch name as blender lts

### ISSUE THREAD

**Issue by andreampiovesana** [CreativeDesigner3D/Library_Home_Builder#39]
Library_CAD_Drawings has branch main, the others master, I propose to make a branch for each blender LTS version
the next will be 2.93

**Comment by CreativeDesigner3D** [comment]
Github made this change. The default trunk is now call 'main' instead of 'master'. maintaining branches for each blender version for each repo might be too much work with little payoff. I typically create tags with each release and notes as to what version it is intended to work for. I will put some thought into this, but do you know of any other add-ons that maintain this structure?

**Comment by aqp696** [comment]
> Github made this change. The default trunk is now call 'main' instead of 'master'. maintaining branches for each blender version for each repo might be too much work with little payoff. I typically create tags with each release and notes as to what version it is intended to work for. I will put some thought into this, but do you know of any other add-ons that maintain this structure?

IMHO, A new git branch for each blender LTS does not make sense with the use of git tags. In the case of this project and it's current git branching strategy, I think that your current workflow creating tags in the `main` branch with the release notes It's the right way to maintain pointers to the released versions. Create a branch to point to an specific version would increase the number of stale branches in the repo.
